### ISSUE TITLE
"antialiasing" of active toggle-button in Chrome

### ISSUE THREAD

**Issue by comerc** [creativetimofficial/material-kit#10]
![toggle-border](https://cloud.githubusercontent.com/assets/1025241/15142515/16bfcf12-16ae-11e6-9be5-dc0d714cd477.png)

**Comment by alexandru-paduraru** [comment]
@comerc please give us more details about the browser/OS. This is how we see them on Chrome v50 MacBook Retina

<img width="664" alt="screen shot 2016-05-13 at 16 08 30" src="https://cloud.githubusercontent.com/assets/2517758/15248829/005ad036-1925-11e6-85e8-74bc056df6c9.png">

Best,
Alex

**Comment by abr4xas** [comment]
Chrome: Version 50.0.2661.102 (64-bit)
OS: Linux Mint

![screenshot - 200516 - 23 50 50](https://cloud.githubusercontent.com/assets/405484/15446208/bb9a6228-1ee1-11e6-9852-3c5b333215a3.png)
