### ISSUE TITLE
Not available in npm

### ISSUE THREAD

**Issue by ArunMj** [creativetimofficial/material-kit#100]
Please make this project available in npm. People are still downloading unofficial https://www.npmjs.com/package/material-kit.

**Comment by alexandru-paduraru** [comment]
@ArunMj thank you! we will do this next week :D

**Comment by mathieuforest** [comment]
Did you create a React components library?

**Comment by alexandru-paduraru** [comment]
@mathieuforest we just release the Material Dashboard, built with Material-UI: https://www.creative-tim.com/product/material-dashboard-react, we will release the UI Kit in a couple of weeks. Please stay tuned!

**Comment by mathieuforest** [comment]
@alexandru-paduraru I bought it today. Thank you very much, its really nice!

**Comment by groovemen** [comment]
Hello @ArunMj,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
