### ISSUE TITLE
broken download link on official demo page?

### ISSUE THREAD

**Issue by cboettig** [creativetimofficial/material-kit#101]
Congrats on launching the Bootstrap 4 versions of Material Kit and Material Kit Pro! Very excited, looking forward to the side-drawer navigation option. 

However, it looks like the download link is broken at: http://demos.creative-tim.com/material-kit/index.html.  Also, the sources here don't seem to reflect the v2.0.0 / BS4 version.

**Comment by dragosct10** [comment]
@cboettig! Thank you for your observation. The link now is fixed and working properly.

Regards, 
Dragos
