### ISSUE TITLE
Bower Install Failed

### ISSUE THREAD

**Issue by avrtrix** [creativetimofficial/material-kit#109]
Hi, I'm trying to do `bower install material-kit` but it still points to https://github.com/timcreative/material-kit.git instead of https://github.com/creativetimofficial/material-kit.git.

![capture](https://user-images.githubusercontent.com/9270059/36776200-e0c9b482-1c9f-11e8-8e10-eac464248971.PNG)

**Comment by dragosct10** [comment]
Hi, @avrtrix! In the meantime, after we released this the GitHub repo was changed and not updated to the bower. Regards, Dragos

**Comment by avrtrix** [comment]
Hello @dragosct10! So I'll just wait for it to be updated, yes?

**Comment by dragosct10** [comment]
Hi, @avrtrix! Yes, we will do an update very soon. Thanks, Dragos

**Comment by dragosct10** [comment]
Hi, @avrtrix! You can try now to install again because made an update. Regards, Dragos

**Comment by groovemen** [comment]
Hello @avrtrix,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
