### ISSUE TITLE
No documentation for v1.2.0

### ISSUE THREAD

**Issue by KeziahMoselle** [creativetimofficial/material-kit#110]
![documentation](https://i.imgur.com/QEV9SKq.png)
When i click on the older documentation, i'm redirected on :
[http://demos.creative-tim.com/bs3/material-kit/tutorial-components.html](http://demos.creative-tim.com/bs3/material-kit/tutorial-components.html)
![where](https://i.imgur.com/vbvtIj7.png)

**Comment by KeziahMoselle** [comment]
Nice, thank's !

**Comment by groovemen** [comment]
Hello @KeziahMoselle,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
