### ISSUE TITLE
Can't display nucleo icons on my website

### ISSUE THREAD

**Issue by ThomasPrs** [creativetimofficial/material-kit#111]
I'm working in local and I can't display any nucleo icon. Did I forget to include something? Did somebody have the same problem?

**Comment by dragosct10** [comment]
Hi, @ThomasPrs! Thank you for using our product. I noticed that you opened this issue in the material kit repo so I think you use the material kit and this product doesn't have the nucleo icons included, it use the material icons. Regards, Dragos
