### ISSUE TITLE
How to add datatables plugins with preserving the design?

### ISSUE THREAD

**Issue by samiurz** [creativetimofficial/material-kit#113]
Hello guys
I was trying to add datatables plugins like file export, multiple row select , date range picker. I  have managed to add them all but due to conflict these two script (https://code.jquery.com/jquery-1.12.4.js,
https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js") i can't wrap them with material design. How can i do add all these plugins without loosing any design?

Thank you

**Comment by dragosct10** [comment]
Hi, @samiurz! Thank you for using our product. What conflicts did you have? Regards, Dragos
