### ISSUE TITLE
No required message on checkbox validation

### ISSUE THREAD

**Issue by MystyxMac** [creativetimofficial/material-kit#114]
I have a checkbox for agreeing to the terms and conditions and want a required message if someone did't check this box.
I've put the required attribute on it and expect a browser default required message as it says in de bootstrap docs. Other fields are working as expected. 

````
<div class="form-check">
    <label class="form-check-label">
        <input class="form-check-input" type="checkbox" value="" required>
        <span class="form-check-sign">
            <span class="check"></span>
        </span>
        I agree to the <a href="#">terms and conditions</a>.
    </label>
</div>
````

**Comment by dragosct10** [comment]
Hi, @MystyxMac! Thank you for using our product. In your example from your input, is missing the `id` and on the span tag is missing the `for` attribute with the value if the `id` like in the [bootstrap example ](https://getbootstrap.com/docs/4.0/components/forms/). Regards, Dragos

**Comment by MystyxMac** [comment]
Hi, thanks for you quick answer, unfortunately it does not work for me. Still no browser warning message for not checking the checkbox.
I put a id attribute on the input tag and a for attribute on the first span tag and tried it also on the second span tag. Both were not successful. 

Any other ideas?
```
<div class="form-check">
    <label class="form-check-label">
        <input id="checkTerms" class="form-check-input" type="checkbox" value="" required>
        <span class="form-check-sign" for="checkTerms">
            <span class="check"></span>
        </span>
        I agree to the <a href="#">terms and conditions</a>.
    </label>
</div>
```

**Comment by MystyxMac** [comment]
I post this a new comment because i have found a solution, but not the way i like/want it.

If I remove the form-check class from the parent div, then the browser warning is working.
But this way I don't have a styled checkbox (It's the browser's default).

Is it possible to use the browser default warnings on styled checkboxes?

**Comment by dragosct10** [comment]
Hi, @MystyxMac! Please, can you give us your link project to see better what happens there? Regards, Dragos

**Comment by MystyxMac** [comment]
This page shows that the default browser validation messages doesn't work for the checkbox. 
The strange this is that is works without the styling... try to remove the form-check class from the parent div of the checkbox.

https://miraku-28-2-20218.appspot.com/contact

**Comment by MystyxMac** [comment]
Thanks, I will try that!

**Comment by dragosct10** [comment]
Hi! This is the library that we use https://jqueryvalidation.org/. Regards, Dragos

**Comment by KannaDinesh** [comment]
I also have the same issue, please rectify..!

**Comment by MystyxMac** [comment]
I end up using the mentioned library.

**Comment by jjansa** [comment]
Not sure if this is still an issue for anyone but I overrode the styling on the checkboxes so the browser validation would be visible. .form-check .form-check-input {
    opacity: 1;
    height: inherit;
    width: inherit;
    overflow: visible;
}
This keeps the material styles and allows the browser validation to be visible.
![Untitled](https://user-images.githubusercontent.com/3476904/56171393-beb32000-5faa-11e9-9774-5e6c7ec8b6d3.png)

**Comment by CodeScroll** [comment]
For my.

That works. https://prnt.sc/s06o51

That doesn't https://prnt.sc/s06oaa
