### ISSUE TITLE
problem with plugin play video 

### ISSUE THREAD

**Issue by mahdiporkar** [creativetimofficial/material-kit#116]
i see in cosole developer this line ` if (!data)`    has error becuase some dome is not standard dom for material kit then `var data = $element.data(DATA_KEY);` result undefined ,
my dom is `<div tabindex="0" class="plyr plyr--video plyr--fullscreen-enabled plyr--stopped plyr--ready"><div class="plyr__video-wrapper" style="cursor: pointer;"><div class="plyr__captions">`
this dom caused error when page loaded,for solving this problem i changed below code in bootstrap-material-design file
          
`   Text._jQueryInterface = function _jQueryInterface(config) {
                    return this.each(function() {
                        var $element = $$$1(this);
                        var data = $element.data(DATA_KEY);

                        if (!data && data!=undefined) {
                            data = new Text($element, config);
                            $element.data(DATA_KEY, data);
                        }
                    });
                };
`

**Comment by groovemen** [comment]
Hello @mahdiporkar,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
