### ISSUE TITLE
Dropdown link icon issue in collapsible navbar

### ISSUE THREAD

**Issue by dmbuchta** [creativetimofficial/material-kit#117]
The CSS for the arrow icon in a dropdown link is incorrectly displayed while in a collapsible navbar. The current css is this:

`.show .dropdown-toggle:after {
    -webkit-transform: rotate(180deg);
    transform: rotate(180deg);
}`

I think the CSS should be more restrictive with the `.show` class. I was able to resolve this for my own project by adding this CSS rule after material-kit.css:

`.navbar .dropdown:not(.show) .dropdown-toggle:after {
    -webkit-transform: rotate(0deg) !important;
    transform: rotate(0deg) !important;
}`

**Comment by groovemen** [comment]
Hello @dmbuchta,
Thank you for your interest in working with our products and for your enhancement. The product was updated to v2.0.4. 
Best, 
Stefan
