### ISSUE TITLE
How to move Sidebar on Small screen from Right side to Left Side?

### ISSUE THREAD

**Issue by roshansingh21** [creativetimofficial/material-kit#118]
Help!!! How to move Sidebar on Small screen from Right side to Left Side?

**Comment by groovemen** [comment]
Hello @roshansingh21, 
thank you for using our products, please follow the next steps:

1. First, you must to go on HTML page and add to body tag the class menu-on-left.

2. Second go to assets/sass/material-kit/_responsive.scss and add the following lines of code:

```
@media (max-width: 991px){
     .menu-on-left{
        &.nav-open{
            .main-panel,
            .navbar-fixed > div{
                @include transform-translate-x(260px);
            }

            .navbar {
                @include transform-translate-x(0px);
            }
        }

        .navbar {
            left: 0;
            right: auto;
            @include transform-translate-x(-260px);
        }
    }
}
```

After you have done this changes, all you have to to is to recompile the project. 

All the best, 
Stefan

**Comment by groovemen** [comment]
Hello again, please integrate the code from the following file instead of the code from above.
[menu-on-left.scss.zip](https://github.com/creativetimofficial/material-kit/files/2159948/menu-on-left.scss.zip)
