### ISSUE TITLE
Upgrading from materialKit 2.0.2 to 2.0.3 just broke everything

### ISSUE THREAD

**Issue by LazosPlaying** [creativetimofficial/material-kit#119]
Alright, so I have reverted back to old state, but when upgrading from 2.0.2 to 2.0.3 just broke everything. All scripts were correctly loaded (most plugins are not included in the .zip file).
It seemed like Bootstrap did not work at all for some reason... I was just plain html-positioning.

If you need more info (which you probably do), please do reply, so I will try to replicate the issue and provide you the files in a .zip file, so you can test it yourself too.

Regards 😃

**Comment by LazosPlaying** [comment]
A lil' update,
When copying stuff from view-source:https://demos.creative-tim.com/material-kit/docs/2.0/components/badge.html things work fine. Maybe check out the "starter template" ([link](https://demos.creative-tim.com/material-kit/docs/2.0/getting-started/introduction.html#starter-template)) if everything is matching with the files in .zip file.

**Comment by groovemen** [comment]
Hello @LazosPlaying,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
