### ISSUE TITLE
Transparent NavBar Color after scroll down

### ISSUE THREAD

**Issue by nyimht** [creativetimofficial/material-kit#120]
I have the transparent navbar currently selected and when I scroll down it turns into an orange navbar. I'd like the navbar to totally disappear after you scroll past 600px. Please help.

**Comment by groovemen** [comment]
Hello @nyimht, thank you for using our products, you have to create your own style to hide the navbar on scroll; please check out this [example](https://medium.com/@mariusc23/hide-header-on-scroll-down-show-on-scroll-up-67bbaae9a78c) and try to reproduce it and integrate into your project.
Best, 
Stefan
