### ISSUE TITLE
DatePicker doesn't always respond to clicks

### ISSUE THREAD

**Issue by rahji** [creativetimofficial/material-kit#122]
I'm trying to use the DatePicker that's on the NOW UI homepage and the one in the documentation and they both seem to have the same problem: It only responds to clicks sometimes. It does provide feedback when I click on different dates, but it only actually changes the date sometimes (rarely). I'm using Chrome Version 66.0.3359.181 (Official Build) (64-bit) on Windows 10.

**Comment by groovemen** [comment]
Hello, please make an update to v2.0.3. It looks like you have some bad files in your project. Please let us know if it worked after this.

Best, 
Stefan

**Comment by rahji** [comment]
This is not my project. I'm looking at the Now UI Kit demo page: https://demos.creative-tim.com/now-ui-kit/index.html

**Comment by groovemen** [comment]
I will ask you to open this issue on the right [repository](https://github.com/creativetimofficial/now-ui-kit). That's why I closed it.
