### ISSUE TITLE
Input type file not working

### ISSUE THREAD

**Issue by ybh1231** [creativetimofficial/material-kit#123]
None of the examples on file input in the documentation works. Neither does it work when downloaded.

However, the the examples on file input in the documentation for the PRO version works fine.

**Comment by Dreamersoul** [comment]
i am having the same issue

**Comment by RamanDhoot** [comment]
i am having the same issue

**Comment by bellalo12** [comment]
having the same issue

**Comment by Dreamersoul** [comment]
i added this to my base js file that runs across the website
```js
$(".inputFileVisible").click(function(){
    $(this).siblings("input[type='file']").click();
});
$(".inputFileVisible").focus(function(){
    $(this).siblings("input[type='file']").focus();
});
$(".inputFileHidden").change(function(){
    if(this.files.length > 0){
        $(this).siblings(".inputFileVisible").val(this.files[0].name);
    }else{
        $(this).siblings(".inputFileVisible").val("");
    }
});
```

**Comment by numerogeek** [comment]
+1

**Comment by groovemen** [comment]
Hello guys,

Thank you for your interest in working with our products, this issue is solved in the latest version (V2.0.4).

All the best,
Stefan

**Comment by tonyrusignuolo** [comment]
I'm using version 2.0.4 and I'm still having this issue.

**Comment by groovemen** [comment]
Hello again, 

it was a misunderstanding, this feature is available only for the PRO version, it was mistakenly left in the documentation, also it had not been added in the product. Sorry about this! 

*we've updated the documentation for the Free version

All the best, 
Stefan

**Comment by tonyrusignuolo** [comment]
Hey Stefan

Thanks for replying. So is there any file input styling for the free version?

Thanks
Tony
