### ISSUE TITLE
Checkbox with required attribute not working

### ISSUE THREAD

**Issue by KannaDinesh** [creativetimofficial/material-kit#124]
Hai, I have an issue, when i try to put checkbox with required attribute , the required functionality does not work, means form submit without validation.

**Comment by groovemen** [comment]
Hello @KannaDinesh ,

Thank you for your interest in working with our products, you have to create the validation for the checkboxes, please check the following [link](https://www.the-art-of-web.com/html/html5-checkbox-required/#example2) to see an example. 

All the best,
Stefan
