### ISSUE TITLE
Uncaught TypeError: $(...).bootstrapMaterialDesign is not a function

### ISSUE THREAD

**Issue by wingyen** [creativetimofficial/material-kit#127]
jquery-3.3.1.min.js:2 Uncaught TypeError: $(...).bootstrapMaterialDesign is not a function
    at HTMLDocument.<anonymous> (material-kit.min.js?v=2.0.3:1)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)

**Comment by groovemen** [comment]
Hello @wingyen,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4). 

All the best, 
Stefan

**Comment by DarthJonathan** [comment]
Has this been fixed? I encountered this on v2.0.4, with webpack

**Comment by mohamadreza89** [comment]
Hi 
I'm using version 2.0.5 and still I'm facing this issue and by the way, I'm using it beside my app.js file (for vue stuffs) . Without including my app.js file it works just fine.

**Comment by groovemen** [comment]
Hello @mohamadreza89, 

Thank you for using our products, I will ask you to check the bootstrapMaterialDesign Github Page and search for the same issue: https://github.com/FezVrasta/bootstrap-material-design/issues. 
Also you can check this link: https://github.com/FezVrasta/bootstrap-material-design/issues/1047

Best, 
Stefan

**Comment by robertBojor** [comment]
@mohamadreza89 I've encountered the same error while using my own app.js file. Including the app.js file before everything else works just fine.

**Comment by NettSite** [comment]
It seems one needs to change the default app.js file to not load Bootstrap:

`/*require('./bootstrap');*/`
