### ISSUE TITLE
Input with floating label ( Mobile Safari ) Loads already Floated. 

### ISSUE THREAD

**Issue by ajmyers01** [creativetimofficial/material-kit#13]
When I load up our floating labels on my Iphone using safari, on the first time it loads all the values are pre-floated, however when I refresh it all looks good and normal. 

Is this a known quirk or is the css/js not loading fast enough? 

Thanks again for the killer theme !

**Comment by alexandru-paduraru** [comment]
@ajmyers01 thank you for the kind words. Here is a print screen from iOS 9.3 on safari. It seems like everything is fine. Can you please give us more details about the issue or how can we simulate it?

![img_9776](https://cloud.githubusercontent.com/assets/2517758/15539116/354cb88c-2289-11e6-88c2-8b5e1e0a02bb.PNG)

Best,
Alex
