### ISSUE TITLE
Javascript links in online documentation not functional

### ISSUE THREAD

**Issue by GianniniCharles** [creativetimofficial/material-kit#130]
I copy pasted the script tags in the getting started page located at https://demos.creative-tim.com/material-kit/docs/2.0/getting-started/introduction.html

Buggy script tags: 

<script src="/assets/js/core/jquery.min.js"></script>
<script src="/assets/js/core/popper.min.js"></script>
<script src="/assets/js/bootstrap-material-design.js"></script>

<script src="/assets/js/plugins/moment.min.js"></script>

<script src="/assets/js/plugins/bootstrap-selectpicker.js"></script>

<script src="/assets/js/plugins/bootstrap-tagsinput.js"></script>

<script src="/assets/js/plugins/jasny-bootstrap.min.js"></script>

<script src="/assets/js/plugins/jquery.flexisel.js"></script>

<script src="/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>

<script src="/assets/js/plugins/nouislider.min.js"></script>

<script src="/assets/js/material-kit.js?v=2.0.3"></script>

When I inserted them into my code, the css kept breaking. I looked at your template file and found the correct tags tags set up, and now it is working.

correct script tags:
<script src="./assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="./assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="./assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="./assets/js/plugins/moment.min.js"></script>
  
  <script src="./assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
  
  <script src="./assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
  
  <script src="./assets/js/material-kit.js?v=2.0.3" type="text/javascript"></script>

**Comment by groovemen** [comment]
Hello @GianniniCharles,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4). 

All the best, 
Stefan
