### ISSUE TITLE
<textarea> causing problems when I do resizing.

### ISSUE THREAD

**Issue by wingyen** [creativetimofficial/material-kit#135]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I need to resize the input area when I input text in my chat app, when the message is sent it should be resized to normal size.

# Current Behavior
I found this in your library:textarea {height: auto!important; } that override my function and disable resizing.

* Operating System: mac os,  ios
* Browser and Version: Google, safari

**Comment by groovemen** [comment]
Hello @wingyen,

Thank you for using our products, if you want to have a resized textarea for your project, please erase the property `textarea {height: auto!important; } ` from our code if it breaks your design. Hope that information helps you. Please let us know if we can help you with anything else.

Best, 
Stefan
