### ISSUE TITLE
onchange event fired multiple times

### ISSUE THREAD

**Issue by Beastw00d** [creativetimofficial/material-kit#136]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When I have an input value with the onchange event being listened to it should fire off once when changed.

# Current Behavior

When I click the input value with the onchange event being listened to it started firing off continually. 

# Failure Information (for bugs)

This happens when there is an input element inside a form. 

I believe it is something to do with the material-kit.min.js script because when that script isn't included it works fine.

## Steps to Reproduce

1. add a form element
2. add an input element inside form 
3. add onchange event to the input element that writes to the console
4. open console and click the input element

```html
<form>
    <input type="text" onchange="console.log('on change fired')" />
</form>
```

here is a plunker to reproduce: https://plnkr.co/edit/Wls1hWw5jlOChqwj7RNU?p=preview

**Comment by groovemen** [comment]
Hello @Beastw00d,

Thank you for using our products, this issue it's from the Bootstrap Material Design library so you need to open an issue on their repository. I reproduce this issue in the video from below to see that it's broken on their product.

[onChange.zip(video)](https://github.com/creativetimofficial/material-kit/files/2366122/onChange.zip)

All the best, 
Stefan

**Comment by luchosrock** [comment]
I think this should be bundled by default with the materialkit js library. Especially in cases when the layout has forms with too many input fields and change event handlers. Hey Creativetim team: may I _PR_ on this? 😺
