### ISSUE TITLE
Running material-kit with webpack 4

### ISSUE THREAD

**Issue by alabama** [creativetimofficial/material-kit#137]
# Prerequisites

- [x] I am running the latest version (2.0.4)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] [hope so] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I would love to see module behavior instead of relying on global 'Popper' and '$'

# Current Behavior

In file: _bootstrap-material-design.min.js_
You started very well with the encapsulated behavior with `require('jquery')` and `require('popper.js')` and giving the dependencies as params. 
Unfortunately there are some calls for the globals calls like `("undefined" == typeof Popper)` or `this._popper = new Popper(a, this._me...`

## Context

I noticed this when using the library with webpack. Here is also a reference that there are some problems with webpack: #85  
I could sill run everything with the ProvidePlugin as well as disabled URL resolve check, cause there is also an error with the path of `cursor: url("../../img/arrow-left.png")`.

Webpack adjustments right now:

```
loader: 'css-loader',
  options: {
  url: false,
  sourceMap: true
}
...
new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery',
  Popper: ['popper.js', 'default']
}),
```

edit: 
I really like the look&feel of your adjustments to the material design.
Keep up the good work!

**Comment by groovemen** [comment]
Hello @alabama, 

Thank you for using our products, please change the URL for the `cursor: url("../../img/arrow-left.png")` that is defined in the CSS file so it will not give you an error.

Best, 
Stefan

**Comment by jorgealemangonzalez** [comment]
I am facing the same issue, I can not manually modify the file because I am using npm....

**Comment by waldekgraban** [comment]
I solved this problem.
Not the path was bad but actually the package I installed lacked the image files in question.

I downloaded the missing files from this repo: 
https://git.ikobb.de/IkoBB/IkoBB/tree/725cf4bb209e5444220be184df8f0fb5aff8661e/template/default/assets
