### ISSUE TITLE
Cannot implement ripple effect other than buttons

### ISSUE THREAD

**Issue by sohan5005** [creativetimofficial/material-kit#141]
Didn't find anything about this on documentation.

Is there any way to implement the ripple click effect on any element I want? Like in materialize I can just add a class to any element and it have the ripple effect. There are also classes to make the ripple dark.

What is the javascript method to initiate the ripple effect?

**Comment by luchosrock** [comment]
AFAIK the ripple effect is part of the bootstrap-material-design library. Try adding the `ripple` class to any element, like this:

```
<div class="ripple">HELLO</div>
```

That will do the trick! 

See this file from the [bootstrapMaterialDesign repo](https://github.com/FezVrasta/bootstrap-material-design/blob/da0896d825cdc39f2e5fb79d03d09d6aa37094e2/js/bootstrapMaterialDesign.js#L64) to see how it works.

I hope it helps 😄
