### ISSUE TITLE
Cannot close modal.

### ISSUE THREAD

**Issue by Kedar-K** [creativetimofficial/material-kit#142]
I am unable to close the modal when is use the model in `class="main"` .
I am using latest chrome and latest material kit. How should i fix this?

**Comment by luchosrock** [comment]
Sometimes the modal behavies weird when you have some event handlers that affect your body content (e.g. jquery on selector change events). Have you tried putting the modal markup _after_ the last `</script>` tag? It worked for me at least. I mean:

```
</div>
<script>
	$(document).ready(function() {
	...
	});
	...	
</script>
<div class="modal hide fade" ....
	...
</div>
...
</body>
```
I hope it helps
