### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by gfsd3v** [creativetimofficial/material-kit#146]
Don't actually now if this is the place to do that, but there's a typo in the documentation link, in the "Build Tolls" section (https://demos.creative-tim.com/material-kit/docs/2.0/getting-started/build-tools.html).

The documentation say the following 

> Run in terminal gulp compile:scss for a single compilation or gulp watch for continous compilation of the changes that you make in *.scss files. This command should be run in the same folder where gulpfile.js and package.json are located.

The gulp code is the following 

```
gulp.task('compile-scss', function() {
  return gulp.src(Paths.SCSS_TOOLKIT_SOURCES)
    .pipe(sourcemaps.init())
    .pipe(sass().on('error', sass.logError))
    .pipe(autoprefixer())
    .pipe(sourcemaps.write(Paths.HERE))
    .pipe(gulp.dest(Paths.CSS));
});
```

Therefore the correct command would be `gulp compile-scss`.

**Comment by groovemen** [comment]
Hello @4rtikk, 

Thank you for using our products and for letting us know about this typo mistake. We will solve this issue in the shortest time. 

All the best, 
Stefan

**Comment by elmima** [comment]
Love the theme but same problem on 
https://demos.creative-tim.com/material-kit/docs/2.1/getting-started/build-tools.html :)

**Comment by groovemen** [comment]
Hello @elmima,

Thank you for your interest in working with our products, it's the same page that was mentioned above. We will solve it shortly.
Best,
Stefan
