### ISSUE TITLE
Issue with JSTree

### ISSUE THREAD

**Issue by liamfl** [creativetimofficial/material-kit#15]
Hi,

You have a really good product which looks great, but I have a problem with a couple of problems with other add ons that use floating panels. I believe you have a fix to get the latest version of the bootstrap-datepicker working, but I have a similar problem wherein the context sensitive menus in JsTree (https://www.jstree.com/) don;t appear when your library is loaded.

Any ideas for a workaround?

Thanks
Liam

**Comment by alexandru-paduraru** [comment]
@liamfl thank you for the kind words. Can you please send us an archive or a link to your product? In this way we will see exactly what is not working on your side and give you a quick fix.

Best,
Alex
