### ISSUE TITLE
Create Sidebar - Help

### ISSUE THREAD

**Issue by smohannagaraj** [creativetimofficial/material-kit#150]
Hello.  First of all thankyou for your kit.
I recently saw your material kit.
I am working on another wordpress website.  I like the sidebars as in demo.  I want to create only sidebars using material kit.  Please guide me.
Thankyou.

**Comment by laubonghaudoi** [comment]
I have the same question here. How to enable a sidebar navigation like the docs in the website?

**Comment by groovemen** [comment]
Hello guys, 

Thank you for using our products, we are sorry for this very late response! The sidebars are available only for admin dashboards product, please check this: https://demos.creative-tim.com/material-dashboard/examples/dashboard.html 
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
