### ISSUE TITLE
Material Kit Pro Select Bootstrap v1.12.2

### ISSUE THREAD

**Issue by jason-cemanes** [creativetimofficial/material-kit#152]
Request adding keyboard event in select option keyboard up & down for selection and space/enter for select the option

https://demos.creative-tim.com/marketplace/material-kit-pro/docs/2.0/plugins/select-bootstrap.html

**Comment by groovemen** [comment]
Hello @jason-cemanes, 

Thank you for using our products, I will ask you to update the plugin first and then please check the following [link](https://stackoverflow.com/questions/38600200/bootstrap-select-and-keyboard-navigation), you'll find the solution for the problem. 
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
