### ISSUE TITLE
impossible to remove fixed-top

### ISSUE THREAD

**Issue by suslikt** [creativetimofficial/material-kit#158]
Hi, use Material Kit Free Version 2.0.5 

If remove fixed-top from
```

<body class="index-page sidebar-collapse">
  <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">...
```

it will broke header design

**Comment by groovemen** [comment]
Hello @suslikt,

Thank you for using our products and sorry for this very late response. In case you didn't find any solution, here you go:

- if you want to remove the "**fixed-top**" class,  you have to change the `navbar-transparent` class with the `navbar-default`
- in order not to have a broken header design, you have to erase the **margin-bottom** of 20px for the .**navbar** class or to set a new property for the navbar: **margin-bottom: 0px !important;**
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
