### ISSUE TITLE
Bugs and inconvenience

### ISSUE THREAD

**Issue by suslikt** [creativetimofficial/material-kit#159]
a)
```
.modal .modal-dialog {
  margin-top: 130px;
}
```
Really? Have you seen how it looks on mobile devices?

Bootstrap 4 has .modal-dialog-centered class, use it instead

b) for centering in the template classes are used is ml-auto mr-auto
It may be more appropriate mx-auto

c) links in modal window don't show cursor:pointer on hover

d) It turns out a very large amount of css and js code and it is difficult to update it when new versions of bootstrap are released.
It would be better to separate the bootstrap and mkit code into different files so people can use the bootstrap CDN, which speeds up the download and allows to take the bootstrap files from the browser cache.

Thanks for your work!

**Comment by groovemen** [comment]
Hello @suslikt,

Thank you for using our products and for your constructive feedback! We will integrate your recommendations into the next update.  Also, we are using Bootstrap Material Desing which is built over Bootstrap so you can't change the Bootstrap version without affecting the product. 
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
