### ISSUE TITLE
Pictures not shows on the documentation page

### ISSUE THREAD

**Issue by rostIvan** [creativetimofficial/material-kit#163]
### Expected Behavior
Looks like here should be an image with example

### Current Behavior
There's no image there, maybe links are broken
![image](https://user-images.githubusercontent.com/25512513/57575895-4a11bb00-745c-11e9-8124-dc4e05313f06.png)

### Failure Information
Link [here](https://demos.creative-tim.com/material-kit/docs/2.1/components/images.html)

**It's not an issue.** But if you would have a free time, you can to quickly solve this. Thanks a lot.

**Comment by groovemen** [comment]
Hello @rostIvan, 

Thank you for using our products and for your constructive feedback, we will solve this issue into the next update, ASAP. Sorry for the inconvenience.Please let us know if we can help you with anything else.

All the best,
Stefan
