### ISSUE TITLE
Header not changing colour on scroll

### ISSUE THREAD

**Issue by mikehobson** [creativetimofficial/material-kit#165]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ ]X I'm reporting the issue to the correct repository (for multi-repository projects)

# issue

When I use the demo page on your website the header canges from having a transparent background to a solid white background when you scroll. When I do this on my test server both in firefox and chrome the header statys transparent and is not visible as the background and the writing are white

* Desktop PC
* Operating System:Windows 10
* Browser and Version: Chrome and firefox

**Comment by groovemen** [comment]
Hello @mikehobson, 

Thank you for using our products, I reproduced this issue but it works fine. I will ask you to share a link to your project to take a look and find a solution. Or you can take a video with the problem. 

All the best, 
Stefan

**Comment by retr0gr4d3** [comment]
I have the same issue, can be observed on:

https://git.retr0.gr4d3.uk/NewNewTest/template.html

OR

https://git.retr0.gr4d3.uk/NewNewTest/

**Comment by groovemen** [comment]
Hello @retr0gr4d3, 

Thank you for using our products, I noticed that you have some errors in the console. The function that triggers the menu to change the background is presented in your main JS file. If you will solve the errors, it will work just fine.

All the best, 
Stefan

**Comment by retr0gr4d3** [comment]
Hi @groovemen,

Thank you for getting back to me so quick. Much appreciated!

This had confused me as it was a direct clone of this repo. Perhaps the file needs updating source side? But thank you for bringing that to my attention. I hadn't thought of checking the console, myself.

Again, much appreciated.
Jake
