### ISSUE TITLE
Windows7 + IE10 Layout Problem

### ISSUE THREAD

**Issue by MinCha** [creativetimofficial/material-kit#166]
Hello.

I am using the pro version.
Our web site URL is "http://your.gg/kr/v4/ea".
As a title, our layout is broken with material-kit on Windows7 + IE10.
There is no problem when I tested on the original bootstrap 4.0. 
In my opinion, especially the Grid is not working.

Could you have any idea?
Thank you for reading.

P.S I bought premium support. It would be great if you guys help fix the problem as soon as possible.

**Comment by groovemen** [comment]
Hello @MinCha, 

Thank you for your interest in working with our products, on readme you can see that we don't offer support for the IE: https://github.com/creativetimofficial/material-kit#browser-support 
Also, it seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well. 

All the best, 
Stefan
