### ISSUE TITLE
Free licence without "Black friday offer" 

### ISSUE THREAD

**Issue by CasperKvolle** [creativetimofficial/material-kit#168]
# I have used the free licence of the material kit and just love it.

But is it not possible to make this pop op going away ?

I run the page that need to be a kind of manegement system and I want to use this template to the layout in the front end and thae backend i have bought a licence for "main" area.

Please help me futher coz I am really in questioning if i bought the right licence and i want to continue to use creative as design template.

www.e-maja.com is the page where the Offer jump out and this is my issue.

Looking farward for your reply.

Best regards 
a very big "creativeTim" fan aka Casper

**Comment by groovemen** [comment]
Hello @CasperKvolle,

Thank you for using our products, I will ask you to point us to the pop up that appears because we checked your page and it looks good. Also, please let us know your order ID to check if your license is right.

Best, 
Stefan

**Comment by CasperKvolle** [comment]
@groovemen  Hey stefan... 

Ahhh ja ok... of coz ... my template that i am using is a MIT licence so currently i am thinking that is why the "pop-op" appears  which is fair enough... 
I cant see anyOrderid in may dashboard but would my email be enough to find my information which is casper@kvolle.com.

I need to buy different licences then please advice me coz i enjoy these templates and this is my choise for thepage:-)

best 
Casper

**Comment by CasperKvolle** [comment]
@groovemen  additional question - reading the "term" for the licence and how i read i need to get an updated paid licence of BOTH Material and the Dashboard to use and distributed on my site ? 
Please advice so i wont run it trouble in the future... want to get the right offers:-)?

**Comment by groovemen** [comment]
Hello again @CasperKvolle, 

That pop-up appears on your project because you copied from our website Google Tag Manager. Please remove all the script that does not belong to you. Related to the licenses, here you have all the information that you need: https://www.creative-tim.com/license. 

All the best, 
Stefan

**Comment by CasperKvolle** [comment]
Hey again @groovemen 

Please advise me on on the status now on my page and what is needed to make the page ok?

Thanks for you fast reply.

best regards 

Casper

**Comment by groovemen** [comment]
Hello again, 

Please download again the product and work over it. 

Best, 
Stefan

**Comment by CasperKvolle** [comment]
Hej
And I cant buy a licens for it as it is now..?
Instead of using free licens.?
Best regards Casper

**Comment by groovemen** [comment]
If you want to have a license, you will get the PRO version of the product, check the following link: https://www.creative-tim.com/product/material-kit-pro 

Best, 
Stefan
