### ISSUE TITLE
Why no release/tag since v2.0.4 (2018-07-02)?

### ISSUE THREAD

**Issue by indyjason79** [creativetimofficial/material-kit#169]
Why has there not been a release/tag since v2.0.4 (2018-07-02)?

I'm using LibMan in Visual Studio to download this package from https://cdnjs.com/libraries/material-kit, but the latest available version is 2.0.4. I'm assuming it's because no one has created a release tag for v2.0.5 or v2.0.6. What gives?

**Comment by groovemen** [comment]
Hello @indyjason79, 

Thank you for using our products and for your constructive feedback. We just created a release tag with the latest version of the product. Sorry for the inconvenience. 
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by indyjason79** [comment]
Thanks Stefan!! I wonder why the version isn't updating at https://cdnjs.com/libraries/material-kit. It's marked as "git autoupdate enabled", so I assumed by you creating a new release it would automatically show up. Currently I'm having to use the manual copy/paste method instead of Libman for your library. 

Just wanted to give you all a heads up on the version issue at cdjns. Thanks for all your efforts!

**Comment by groovemen** [comment]
Hello again, 

Until we will fix this issue, we'll ask you to use the following link: https://raw.githubusercontent.com/creativetimofficial/material-kit/master/assets/css/material-kit.min.css for having the style working like a CDN. 

Best, 
Stefan
