### ISSUE TITLE
Hi Creative Tim, I've downloaded a few of your Material Design kits because they are fabulous!... but I'm never able to use them, I don't know how. I'm skilled in HTML and CSS and when I need some jQery Code or js, I find the code I need and paste it in. So unless I'm starting a website from scratch, I don't think I'm able to just upload your documents to an existing site and change the look of it. Do you agree? Or do you have documentation of steps to follow for someone like me?

### ISSUE THREAD

**Issue by brilliantindication** [creativetimofficial/material-kit#179]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello there, @brilliantindication 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan
