### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by Situma** [creativetimofficial/material-kit#20]
The menu is not clickable once viewed in mobile

**Comment by alexandru-paduraru** [comment]
@Situma thank you for the information. Can you please give us more details? Which menu, what device and what is the OS? In this way we can test your issue. 

Best,
Alex

**Comment by Situma** [comment]
Hi @alexandru-paduraru , 
On both my ipod and my xperia z2 the page becomes responsive in a lovely way but the menu cannot dropdown to show it's links.
I also tried to inpect element and adjusted the screen size on chrome to emulate a mobile phone but still the issue is the same.

**Comment by rallixt** [comment]
@alexandru-paduraru , I'm new to the whole gethub thing, but I found the components-documentation.html was missing the data-toggle="collapse" attribute for the navbar hamburger button and it prevented it from expanding the menu when collapsed. I have updated it locally but I don't know how and or have the permissions to upload it to submit a pull request. Hopefully this helps.

**Comment by alexandru-paduraru** [comment]
@rallixt thank you for the PR, that is the right way of giving us a help with code. We will add your change for the next release.

Best,
Alex
