### ISSUE TITLE
[Bug] Table doesn't wrap contents and runs off side of screen when placed inside a card

### ISSUE THREAD

**Issue by MarkRadaba** [creativetimofficial/material-kit#215]
### Version
3.0.3
### Reproduction link
https://manage.glendaleheights.org/temp/news-temp.aspx
### Operating System
Windows 11
### Device
PC
### Browser & Version
Microsost Edge
### Steps to reproduce
1. Create page using Material Dashboard 2 UI Kit.
2. Generate card element in page.
3. Insert table in card, containing several columns.
4. Insert large amounts of text in columns.  Cell contents are not wrapped so text appears in one line, causing table to expend past the edge of the screen.
### What is expected?
Contents of cells in table to wrap so table does now expand past side of card
### What is actually happening?
Text in table cells does not wrap and table extends outside of card and beyond edge of screen.

---
### Additional comments
Behavior works correctly in "vanilla" Bootstrap 5.  Issue only happens when using Material Dashboard 2 UI kit.

**Comment by groovemen** [comment]
Hello @MarkRadaba, thank you for using our products, please try to wrap the `<table class="table table-sm table-striped table-bordered">...</table>` into a `<div class=table-responsive></div>`.
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
