### ISSUE TITLE
Dropdown Submenu

### ISSUE THREAD

**Issue by sldobri** [creativetimofficial/material-kit#23]
How i add???

**Comment by alexandru-paduraru** [comment]
@sldobri thank you for using our product. At this moment we don't have that feature implemented. I recommend you to check this plugin which is giving you the option to add sub-menus: https://vsn4ik.github.io/bootstrap-submenu/

Please let us know how is the integration working.

Best,
Alex

**Comment by fanvyr** [comment]
Would appretiate a sub menu structure support! Or maybe more styling options (columns, ...)
