### ISSUE TITLE
Please, use another datepicker plugin

### ISSUE THREAD

**Issue by victorwpbastos** [creativetimofficial/material-kit#30]
The datepicker plugin that you guys chose seems to be abandoned. There's many others that are being maintained actively and offer more options (localization for example). I suggest to change the datepicker plugin to https://github.com/eternicode/bootstrap-datepicker.

**Comment by lembitk** [comment]
+1

**Comment by PeterKitonga** [comment]
Please consider adding support for bootstrap datetimepicker as well: https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by azaruiz94** [comment]
I´m having a serius headache trying to configurate the language to spanish

**Comment by groovemen** [comment]
Hello @azaruiz94, 

Thank you for using our products, I will ask you to check the [documentation of the datepicker](http://eonasdan.github.io/bootstrap-datetimepicker/), and have in mind the following link: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/565 

All the best, 
Stefan
