### ISSUE TITLE
Read-only input fields

### ISSUE THREAD

**Issue by anotheri** [creativetimofficial/material-kit#31]
Read-only input fields look absolutely the same way as active fields.

**Comment by alexandru-paduraru** [comment]
@anotheri great catch! Thank you. We will update it in the next release. Till then please open material.min.js and find this:

```  i.prop("disabled")||i.closest(".form-group").addClass("is-focused") ```
and replace it with this:
``` i.prop("disabled")||i.prop("readonly")||i.closest(".form-group").addClass("is-focused") ```

Best,
Alex
