### ISSUE TITLE
Size modifiers for "just-icon" buttons 

### ISSUE THREAD

**Issue by anotheri** [creativetimofficial/material-kit#32]
If i add class `btn-xs`, `btn-sm` it won't affect button with styles like this: `btn btn-just-icon btn-round`; and `btn-lg` affects it wrong way. Fix, please.

**Comment by alexandru-paduraru** [comment]
@anotheri thank you for pointing out. We've checked and for "btn-just-icon" we didn't implement at all the sizes, we will fix them in a future update. 

Best,
Alex
