### ISSUE TITLE
make it available from CDN

### ISSUE THREAD

**Issue by Hermanya** [creativetimofficial/material-kit#34]
Copying an import link would be so much more convenient than downloading your zip.

**Comment by alexandru-paduraru** [comment]
@Hermanya thank you for using our product. We will take this into consideration. Do you have any suggestion for a CDN company?

**Comment by Hermanya** [comment]
I'm not using it yet. But I would, if it was hosted on cdnjs.
Also bower/npm.

**Comment by FezVrasta** [comment]
Actually you could just use the rawgit CDN.

https://cdn.rawgit.com/timcreative/material-kit/master/assets/css/material-kit.css
