### ISSUE TITLE
Changing Color

### ISSUE THREAD

**Issue by ebae94** [creativetimofficial/material-kit#35]
Is there a direct way to change the purple color used througout the template without having to modify all the places where it appears in the css file?

**Comment by alexandru-paduraru** [comment]
@ebae94 yes, you can do that in assets/sass/material-kit/_variables.scss ```$brand-primary: $purple !default;``` and change the brand-primary with any color that you want. You can find material colors in _colors.scss or you can add the Hex color code. To compile the new SCSS we are using [Koala](http://koala-app.com/).

**Comment by iamthestreets** [comment]
@alexandru-paduraru I am also using Koala. I added the _variables.scss to Koala and made a change. It compiles the file into a css file but it only shows this:
```
/* ANIMATION */
/* SHADOWS */

/*# sourceMappingURL=material-kit-blue.css.map */
```

What am I missing?

**Comment by Firestorm-Graphics** [comment]
$brand-primary: is the only places the color purple is used, theres multiple scss files where its used in a gradient i.e cards

**Comment by Wiesenlooser** [comment]
Hey - I'm not really sure how to change the color :/ 

I'm not really good at programming. What exactly do you mean with "compiling" the new SCSS using Koala? I don't really know about Koala. I just want to get rid of that purple colour ^^

**Comment by Firestorm-Graphics** [comment]
you might want to google how to use sass as this isnt the place for tutorials, but if you want to just change the css file then you can do a find and replace in your text editor

**Comment by tau150** [comment]
Which is the archive to change in version that uses bootstrap 4 ?, material kit folder doesnt exist.
