### ISSUE TITLE
Radio Button/Checkbox disappear when the radio button/checkbox is rendered using Angular ng-repeat

### ISSUE THREAD

**Issue by rajshrimohanks** [creativetimofficial/material-kit#43]
I'm rendering some radio buttons and checkboxes using AngularJS' `ng-repeat`. The labels appear fine but the circle/square to click on does not appear. On inspecting the console, I found that the

```
<span class="circle"></span>
<span class="check"></span>
```

appended after the `<label>` is not appended when using `ng-repeat`.

How should I be getting around this?

**Comment by rajshrimohanks** [comment]
Further inspection revealed that it was due to the fact that the radio buttons are styled by using JS in material kit. The JS loads and runs before the angular code could be rendered and hence this issue. I set a timeout to load the JS after a second which should give angular enough time to render and sure enough, it works now. It's a dirty hack, so I'm trying to figure out a better way to do it.

**Comment by alexandru-paduraru** [comment]
@rajshrimohanks thank you for using our product. When you are using Angular and the material js is called later, please also use the arrive.js library, how our collaborator Federico (the original creator of the Material Design Bootstrap) specify here: https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support

Hope that helps you!

All the best,
Alex

**Comment by dbarrett24** [comment]
@alexandru-paduraru could you show me how to do that? I'm having many similar issues with angular and the checkboxes/animations not showing up.

**Comment by alexandru-paduraru** [comment]
@dbarrett24 if you have an Angular project please check how we integrated the elements in our Material Dashboard Angular 2: https://github.com/creativetimofficial/material-dashboard-angular

Best,
Alex
