### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by anartfulscience** [creativetimofficial/material-kit#47]
Hello,

Is this just for Bootstrap 3? I'm getting compile errors using v4.

Thanks, Stephen

**Comment by alexandru-paduraru** [comment]
@anartfulscience thank you for using our product. We just responded to your email too. The kit is compatible with BS3 at this moment. Please give us any information that you have like folder structure, SCSS compiler name, OS, line of the errors etc, so we can check and see if we can give you a fix.

All the best,
Alex

**Comment by anartfulscience** [comment]
Hi Alex,

I've got it working. I believe I missed one of the js files so it through the UI.

Regards customising the colours I'm using some standard bootstrap variables before I bring in your scss. E.G $brand-primary $brand-success, ect. But it doesn't seem to be updating your colours. 

Are you using difference variables to bootstrap?

Thanks, Stephen

**Comment by alexandru-paduraru** [comment]
@anartfulscience sorry for the late response. Good to know that they are working fine with all the JS file. To change the colors please go to assets/scss/_variables.scss and you will find the starting with line 26 the variables. They are set using ```$purple, $green, $red etc. ``` which are set in _colors.scss.

Please let us know if you've got it right.

Best,
Alex
