### ISSUE TITLE
parallax on index page disables when removing the sliders

### ISSUE THREAD

**Issue by StijnKeppens** [creativetimofficial/material-kit#49]
Hi there,
I started my development, based upon the index-template.
When I remove the slides that were added on the page, the parallax effect is lost.
I solved this by putting it in a display:hidden-div, but seems strange...
Any idea how I could solve this? I like the kit very much!
Best regards and thanks for your help.
Stijn

**Comment by alexandru-paduraru** [comment]
@StijnKeppens thank you for using our product. We've also removed the slides carousel from it and it is working fine. Please send us a link with your website so we can check. Also, make sure you don't have any javascript errors in the Developer console on Chrome/Firefox.

Best,
Alex

**Comment by StijnKeppens** [comment]
Hi Alex,
Thanks for looking into this.
I just re-downloaded the kit, put it on my webspace and set the sliders in comment.
Just doing that, I get a javascript error (noUiSlider: Can't initialize slider on empty selection) and loosing parallax. 
http://luiehond.be/vwcalifornia/obsolete/test/index.html

How should I remove this not creating the js error?

Best regards.
Stijn

**Comment by Gui-sf** [comment]
Hi @StijnKeppens, 
You said you use the "index-template" ? 
Might it be possible you got this script: 
`<script type="text/javascript">

		$().ready(function(){
			// the body of this function is in assets/material-kit.js
			materialKit.initSliders();
            window_width = $(window).width();

            if (window_width >= 992){
                big_image = $('.wrapper > .header');

				$(window).on('scroll', materialKitDemo.checkScrollForParallax);
			}

		});
	</script>`

If it's the case juste remove "materialKit.initSliders();" from it and it will work fine.
Sorry if it's a bit late for you, but might be useful for other people :)

**Comment by StijnKeppens** [comment]
Big thanks @Gui-sf 
Works perfectly now!
