### ISSUE TITLE
Changing Variables and Compiling

### ISSUE THREAD

**Issue by beginnerdev** [creativetimofficial/material-kit#51]
Hello, Im new to SCSS and am unsure of how does it work. Im currently using atom.
I have tried to change the primary colour to $light-blue and have tried to compile but there is an error saying 'node-sass' is not recognized as an internal or external command, operable program or batch file.

May i know is there any possibility that i could change all scss files to css files to work on or must it be scss?

**Comment by alexandru-paduraru** [comment]
@beginnerdev thank you for using our product. Please use this compiler: http://koala-app.com/ and let us know if that is working fine. We were using it on all our products and we didn't have any issues with it.

Best,
Alex

**Comment by beginnerdev** [comment]
![image](https://cloud.githubusercontent.com/assets/24800881/21874163/4f358aea-d8ae-11e6-8c53-859e351dc9b5.png)

@alexandru-paduraru  hello, when i tried to compile, it gives me the following error.

**Comment by alexandru-paduraru** [comment]
@beginnerdev please compile `assets/sass/material-kit.scss` not the files with "_" in front of them and let us know your status.

Best,
Alex

**Comment by beginnerdev** [comment]
![image](https://cloud.githubusercontent.com/assets/24800881/22048615/14d4f574-dd69-11e6-84a9-01e8ec32d9a4.png)

@alexandru-paduraru Hello, im still unable to compile the file

**Comment by alexandru-paduraru** [comment]
@beginnerdev that's weird. Please try to rename the folder with "material-kit-master - Copy" with something that doesn't have any spaces in it. Also set the output style of SASS to extended and uncheck the "Source Map" option, then check to compile again.

**Comment by alexandru-paduraru** [comment]
@beginnerdev please also check Stackoverflow or google with that error: http://stackoverflow.com/questions/32853703/gulp-ruby-sass-sass-is-not-recognized-as-an-internal-or-external-command-op it seems there is something missing from your computer. 

Best,
Alex

**Comment by hetmann** [comment]
@beginnerdev have you tried using atom `sass-autocompile` from https://atom.io/packages/sass-autocompile ?

**Comment by beginnerdev** [comment]
@alexandru-paduraru hey, i still cant seem to find any solution.

@hetmann Yup have tried, still have the same error.

**Comment by alexandru-paduraru** [comment]
@beginnerdev did you try to install all the missing items from your computer? Here is the link: http://stackoverflow.com/questions/32853703/gulp-ruby-sass-sass-is-not-recognized-as-an-internal-or-external-command-op

**Comment by beginnerdev** [comment]
@alexandru-paduraru Alright have finally install the missing items! Thank you!

**Comment by alexandru-paduraru** [comment]
@beginnerdev that's great! Good luck with further development :D
