### ISSUE TITLE
Basic version of material kit allows color overrides, pro ignores them

### ISSUE THREAD

**Issue by gamut** [creativetimofficial/material-kit#55]
With the basic version and SCSS I could put some colour overrides in front of material-kit but after bootstrap, and it used them.  The Pro version seems to overwrite them somewhere.  Can you please comment somewhere in the docs where those should be imported or placed?  There is such a plethora of files, and orphaned files, that it's hard to tell.

**Comment by gamut** [comment]
Apparently the PRO version requires that you specify the color of some components as "primary", instead of it defaulting like it does in bootstrap... I think you should keep things consistent with BS.

**Comment by alexandru-paduraru** [comment]
@gamut thank you for using our product. There is in the archive of the PRO version a `tutorial-components.html` file which has this explanation for the colors:

```html
You can change the default colors via variables from SASS:

1. You can find the colors in assets/sass/material-kit/_variables.scss starting with line 28 where is the primary color set: $brand-primary: $purple !default;. All the possible colors are in assets/sass/material-kit/_colors.scss
2. Add the SASS folder from assets/sass/ to a new project inside Koala Compiler and find the file material-kit.scss, it will be the one in Green.
3. Right click on that file and set the output path, it must be in assets/css/ so anything that you compile will overwrite the original material-dashboard.css
4.Press on compile and everything will be done automatically. 
```

Please let us know which files are orphaned so we can check them and see where they belong and if we should link them back or delete them, so they don't confuse the future users.

Alex
