### ISSUE TITLE
Instant validation with selects

### ISSUE THREAD

**Issue by minikN** [creativetimofficial/material-kit#56]
Hello,

I'm having troubles getting a select input to work how other inputs work. On a regular input (Type = text) the field gets validated on every keystroke (I have uploaded a short gif to show what I mean). 

![ezgif com-242d6d2c81](https://cloud.githubusercontent.com/assets/1888338/22443254/925e4cc8-e73e-11e6-9d09-4bee915991c3.gif)

I think this is how you guys designed it in material.min.js. However, is it also possible to achieve that with a multiple select field? I'm using bootstrap select js plugin and I'm having a hard time getting this to work. The problem is that the classes 'has-succuess' and 'has-error' don't get applied to the form-group div. Neither does the error/valid class from the validate plugin get applied to the select itself.

Mind you, it works when I click the submit button. But I'd like to make this work on focusout, or rather on change as well. So whenever I check/uncheck an option it should get validated.

Since this is working out of the box with other inputs I thought i'd ask here first.

Thanks.

**Comment by alexandru-paduraru** [comment]
@minikN thank you for the observation. Our product was built on top of [Bootstrap Material Design](https://github.com/FezVrasta/bootstrap-material-design), so the material.min.js wasn't built by us. What we can recommend you is to add the [jQuery Validation Library](https://jqueryvalidation.org/) and add the class .has-success/error to the parent field of the bootstrap select (form-group div). jQuery Validation will be activated as soon as you click on the select. Here are some answers for this: http://stackoverflow.com/questions/18315242/validation-of-bootstrap-select-using-jquery-validate-plugin

Hope this information helps you.

Best,
Alex

**Comment by minikN** [comment]
It's working. Thanks Alex.

I have another question which is not really an issue, so I don't want to open another issue for it. Hopefully it's okay to ask you here:

Can you tell me what flags pack you used here?

![bildschirmfoto 2017-01-31 um 01 26 21](https://cloud.githubusercontent.com/assets/1888338/22447727/80fcd100-e754-11e6-9381-16daad7055b1.png)

**Comment by alexandru-paduraru** [comment]
@minikN yes, you can ask here, no problem. We used the pack made by the guys from Stripe which can be found here: https://dribbble.com/shots/1089488-Stripe-Flag-Set
