### ISSUE TITLE
Uncaught TypeError: $ is not a function  at material-kit.js

### ISSUE THREAD

**Issue by creativjam** [creativetimofficial/material-kit#57]
Great set of components, but I am getting this error : Uncaught TypeError: $ is not a function  at material-kit.js

The navigation toggl, is not working, and I think it could be something to do with this file? as normal Bootstrap Dropdown works. - Using with WordPress

[link here](http://b.wearemiddle.com/sensory2)

**Comment by alexandru-paduraru** [comment]
@creativjam thank you for using our product. It seems you don't have the right jQuery library, which is needed for our UI kit. Please make sure you include all the files that are necessary for the Kit to work. 

<img width="1124" alt="screen shot 2017-02-09 at 10 14 35" src="https://cloud.githubusercontent.com/assets/2517758/22774670/d49a36fa-eeb0-11e6-9e81-51bc7c8a5814.png">

Here is also a fix from stackoverflow: http://stackoverflow.com/questions/12343714/typeerror-is-not-a-function-when-calling-jquery-function

Also, you can check this Wordpress version made by one of our collaborators: http://mvpwp.com/products/materialkitwp/ 

Hope this information will help you.

Best,
Alex
