### ISSUE TITLE
noUiSlider doesn't create tooltips

### ISSUE THREAD

**Issue by utkapodsousom** [creativetimofficial/material-kit#61]
It is supposed to append a div with noUi-handle class when there is an 'tooltips' option is set to 'true', but it doesn't. Please, help with figuring this out.

**Comment by alexandru-paduraru** [comment]
@utkapodsousom thank you for using our product. We've checked and you're right, the nouislider.min.js doesn't contain the tooltips at all, that means we either used an old version of NoUISlider or the [original Bootstrap Material Design repo](https://github.com/FezVrasta/bootstrap-material-design) that we used to build [Material Kit](https://www.creative-tim.com/product/material-kit/) used a version of NoUISlider that didn't contain the tooltips. 

If you really want the tooltips, you can contribute to this repo, it is open source, so we need the help of the community to make it better. You can upgrade the library to the latest version and then send us a pull request. We will check it and so some tests and if everything is fine we will add you as a contributor and other users will benefit from your changes.

Please let us know if you have any further questions.

Best,
Alex

**Comment by utkapodsousom** [comment]
@alexandru-paduraru Thank you for your answer. I would definitely contribute if I knew the code. But since I'm not a developer I cant. Just need mentioned functionality. It would be great if someone who knows the stuff contribute to this. 

Other than that I appreciate your product. It is really good!
