### ISSUE TITLE
Erroneous CSS `color` values due to a missing SASS partial/function

### ISSUE THREAD

**Issue by lembitk** [creativetimofficial/material-kit#62]
1. As the [`_mixins-utilities.scss`](https://github.com/FezVrasta/bootstrap-material-design/blob/master/sass/_mixins-utilities.scss) file from the [bootstrap-material-design](https://github.com/FezVrasta/bootstrap-material-design) project is missing, 
1. SASS [function `contrast-color()`](https://github.com/creativetimofficial/material-kit/blob/3acc49ddd3f65a16de611e5d4fd47c430dc598ae/assets/sass/material-kit/_mixins.scss#L52) is not available, 
1. resulting in erroneous `color` declaration values like [`color: contrast-color(#3f51b5, #000000, #ffffff)`](https://github.com/creativetimofficial/material-kit/blob/f2853b5c9cc5f3cbad88f61c0865b2fe3c0c0dd5/assets/css/material-kit.css#L2144) in the compiled CSS (8 occasions/lines). 

The fix is to add the `_mixins-utilities.scss` file to the project, `@import '_mixins-utilities'` in the beginning of the `_mixins.scss` file, and then recompile CSS. 

I will open a PR with the fix.

**Comment by alexandru-paduraru** [comment]
@lembitk thank you for pointing out and for the PR. I've checked and it is right, we will add that in the next update release v1.2.0. 

Best,
Alex
