### ISSUE TITLE
Navigation issue in the tabs

### ISSUE THREAD

**Issue by isantiagoo** [creativetimofficial/material-kit#64]
¡Hey! I need your help pleaseee. Im doing a system in php and i decide to use this template to make the ID so im trying to put forms into the section of the tabs. And it work really well. But when im gonna try to add a new form into the second id (#). 

`<div class="tab-pane" id="messages"> Here </div>`
																			
Even if i copy and paste the same form that works in the first tab. The tabs do not work anymore and stay static in the first tab. IDK why this happens and i notice that when i put the second form or anything else that is not a plain text the 

`<li class=""> </li>` 

that should change to

`<li class="active"> </li>` 

In the div of tabs it doesnt change anymore 

and the class property of aria-expanded="true" do not change too

`<a href="#profile" data-toggle="tab" aria-expanded="false">`

that should change to

`<a href="#profile" data-toggle="tab" aria-expanded="true">`

Also i notice that if you see the url of the page when is only a one form when i click on the tabs the "clientes#profile" for example in the end of the url does not change even if i click in the differents tabs. Instead when i put the other form start change it to the respective "id = #" when i clic on every tab. 

The thing is that im lost im trying a lot of stuff but i guess that is something of the js idk i add the complet file here
[doctype html.docx](https://github.com/creativetimofficial/material-kit/files/948791/doctype.html.docx)

Thanks and have a nice day coders!

**Comment by alexandru-paduraru** [comment]
@isantiagoo thank you for using our product. Please align and indend the code before sending it or give us a link yo your website. I've checked and you have a lot of divs that are not closed right:

<img width="1155" alt="screen shot 2017-04-22 at 20 19 50" src="https://cloud.githubusercontent.com/assets/2517758/25306607/2d447362-2799-11e7-9bd2-642dec406760.png">

Waiting for a better version. Please make sure you use this structure:

```html
<div class="card card-nav-tabs">
	<div class="header header-success">
		<div class="nav-tabs-navigation">
			<div class="nav-tabs-wrapper">
				<ul class="nav nav-tabs" data-tabs="tabs">
					<li class="active">
						<a href="#profile" data-toggle="tab">
							<i class="material-icons">face</i>
							Profile
						</a>
					</li>
					<li>
						<a href="#messages" data-toggle="tab">
							<i class="material-icons">chat</i>
							Messages
						</a>
					</li>
					<li>
						<a href="#settings" data-toggle="tab">
							<i class="material-icons">build</i>
							Settings
						</a>

					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="content">
		<div class="tab-content text-center">
			<div class="tab-pane active" id="profile">
				<p> I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. </p>
			</div>
			<div class="tab-pane" id="messages">
				<p> I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.</p>
			</div>
			<div class="tab-pane" id="settings">
				<p>I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. So when you get something that has the name Kanye West on it, it’s supposed to be pushing the furthest possibilities. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus.</p>
			</div>
		</div>
	</div>
</div>
```
With all the divs closed right.

Best,
Alex
