### ISSUE TITLE
Erroneous black cross in Success and Error inputs

### ISSUE THREAD

**Issue by tubeway1964** [creativetimofficial/material-kit#66]
Using IE 11 - Success and Error fields show a black cross underneath the success/error images (see attached images)
![ctim_error](https://cloud.githubusercontent.com/assets/28338834/25651734/8292768e-2fdc-11e7-94c2-ab7b9db758dd.png)
![ctim_ie](https://cloud.githubusercontent.com/assets/28338834/25651732/828f4a40-2fdc-11e7-98bb-0d615d651f8b.png)
![ctim_success](https://cloud.githubusercontent.com/assets/28338834/25651733/82924c22-2fdc-11e7-9555-d0b0a49a7fdb.png)

**Comment by dragosct10** [comment]
Hi @tubeway1964 ! I will attach a file that will fix this bug for you and what you have to do is to replace in the project `assets/material-kit/_inputs.scss` the partial `_inputs.scss` with the new one. Please compile your scss with [Koala](koala-app.com) and be sure that the output path is `assets/css/material-kit.css`. Hope that everything will work fine! 

[_inputs.scss.zip](https://github.com/creativetimofficial/material-kit/files/974124/_inputs.scss.zip)
