### ISSUE TITLE
Datepicker options not working

### ISSUE THREAD

**Issue by moko11** [creativetimofficial/material-kit#67]
material-kit.js
```
if($('.datepicker').length != 0){
        $('.datepicker').datepicker({
             weekStart:1
        });
    }
```
If I am adding any other option like `autoclose: true`, it seems to have no impact on the datepicker.

(I just uploaded a fresh version of Material Kit to make sure the bug is not related to any other changes in the code that I've done before)

**Comment by alexandru-paduraru** [comment]
@moko11 thank you for using our product. Where did you find that the datepicker has the `autoclose` method in this documentation: http://www.eyecon.ro/bootstrap-datepicker/? I cannot find that :-(

Best,
Alex

**Comment by moko11** [comment]
Oh I just recognized that I was checking the documentation of another datepicker with the same name which has way more options (https://bootstrap-datepicker.readthedocs.io/en/latest/options.html).

So all options provided in your documentation are working. Sorry for the confusion!

Best
Moritz
