### ISSUE TITLE
Can I use Material Kit with Bootstrap V4?

### ISSUE THREAD

**Issue by artfulcat** [creativetimofficial/material-kit#69]
Hi.

I use Bootstrap4alpha6 inside my WordPress style.scss (it contain bootstrap styles inside), like this:
@import "bootstrap/bootstrap.scss";
@import "my-styles-1";
@import "my-styles-2";

Can I use Material Kit with Bootstrap V4? How?

I have scss-error in "/material-kit/_variables_bootstrap.scss": px & rem. I think it conflict with "/bootstrap/_variables.scss".

How does it correct?

**Comment by artfulcat** [comment]
When I use material-kit.css the site was working, but .dropdown-menu is invisible. Material-Kit for Bootstrap V3 only? Do you have V4 branch?

**Comment by alexandru-paduraru** [comment]
@artfulcat thank you for your interest in our product. Unfortunately, Material Kit is not developed for Bootstrap 4 yet, we will migrate it to BS4 in the next weeks. 

Best,
Alex
