### ISSUE TITLE
Material Kit's .navbar overrides Bootstrap's .navbar-static-top border-radius

### ISSUE THREAD

**Issue by miniahmet** [creativetimofficial/material-kit#70]
_.navbar-static-top_ don't works normally with Material Kit. Material Kit's _.navbar_ overrides Bootstrap's _.navbar-static-top_ and _border-radius_ not removed and navbar looks ugly.

**Comment by alexandru-paduraru** [comment]
@miniahmet thank you for pointing out. Please add this class at the end of material-kit.css

.navbar-static-top{
border-radius:0px !important;
margin-bottom: 0px;
}

Then everything will look fine.

Best,
Alex
