### ISSUE TITLE
Bootstrap Modal is not working.

### ISSUE THREAD

**Issue by tHe-AK** [creativetimofficial/material-kit#71]
Modal is visible but not clickable and modal-backdrop class comes over modal

**Comment by dragosct10** [comment]
Hi @tHe-AK! For fixing this issue I will upload the javascript file `material-kit.js` which is modified and please go in `assets/js/material-kit.js` and replace this with the new one. Hope that will help you and please let us know if everything is working fine! 

[material-kit.js.zip](https://github.com/creativetimofficial/material-kit/files/1057582/material-kit.js.zip)

Regards,
Dragos

**Comment by ChristoPy** [comment]
I have the same issue. Even replacing the file as said above, it keeps the same

**Comment by dragosct10** [comment]
Hi, @ChristoPy! Thank you for using our product. Please, give us your link to see what happened there. Regards, Dragos
