### ISSUE TITLE
about progress bar

### ISSUE THREAD

**Issue by karlos1113** [creativetimofficial/material-kit#72]
Hello,
I am doing a small project in my school by using basic material-kit andI bet it is one of best bootstrap theme I've ever used.
However, while I am using 'progress bar' in the kit, I think it can be better if this bar can support 'mouse over text'.  What I meant to say is hover text feature.  
Is there any reason why you didn't put this feature in the progress bar?

**Comment by groovemen** [comment]
Hello @karlos1113, thank you for using our product, you have an example at the following [link](https://jsfiddle.net/aj4w9c3L/2/)

Best,
Stefan
