### ISSUE TITLE
checkbox

### ISSUE THREAD

**Issue by cesarmf** [creativetimofficial/material-kit#76]
checkbox does not appear when using in a table within a card-content. I am rendering the code dynamically so that the I have <div class="checkbox"> but the underlying tags and their classes <span class="checkbox-material">  <span class="checkbox"> do not render and a checkbox does not appear o the screen. Removing <div class="checkbox"> shows a default form textbox

**Comment by cesarmf** [comment]
using php to render the page:                              
                                    echo'<tr>';
                                        echo'<td>';
                                           // echo '<div class="form-group">';
                                                echo'<div class="checkbox ">';
                                                    echo'<label>';        
                                                        echo'<input type="checkbox" name="optionsCheckboxes" >';
                                                    echo'</label>';
                                               echo'</div>';
                                           // echo '</div>'; 
                                        echo'</td>';
                                        echo'<td>';
                                            echo'this is my first task.this is my first task.this is my first task. ';
                                        echo'</td>';
                                        echo'<td  class=" td-actions text-right">';                                          
                                            echo'<button type="button" rel="tooltip" class="btn btn-simple btn-danger ">';
                                                echo'<i class="material-icons text-right">delete_forever</i>';
                                            echo'</button>';
                                        echo'</td>';
                                     echo'</tr>'; 


![checkboxissue](https://user-images.githubusercontent.com/26068785/27878067-fcec657c-618a-11e7-92e6-dfe915a5b467.PNG)

**Comment by alexandru-paduraru** [comment]
@cesarmf thank you for using our product. For dynamic elements please add the arrive library: https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support 

Best,
Alex
