### ISSUE TITLE
Checkbox disappear when using vue router + v-for

### ISSUE THREAD

**Issue by dhiraj1mumbai** [creativetimofficial/material-kit#79]
Hi,

I am using vue js with this theme and loading vue template via vue-router. 

I am also generating textbox dynamically using v-for.

But when I do so, checkboxes disappear but labels are there. 

Is there any way I can fix this.

**Comment by alexandru-paduraru** [comment]
@dhiraj1mumbai please add the Arrive.js library for dynamic content: https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support then it will work fine.
