### ISSUE TITLE
Seem issue at floating lable with Datepicker control?

### ISSUE THREAD

**Issue by abhishekbhalani** [creativetimofficial/material-kit#80]
Seem issue at floating label with Datepicker control?
please check it.

the floating label don't go up when date has been selected.

**Comment by alexandru-paduraru** [comment]
@abhishekbhalani thank you for pointing out. We confirm this is a bug and we will fix it in the next product update. In the meantime, you can add inside the date picker "change" function an action that will remove the "is-empty" class from the form. Hope this gives you an idea about how to fix it. Let us know if that was working fine for you.

Best,
Alex

**Comment by groovemen** [comment]
Hello @abhishekbhalani,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
