### ISSUE TITLE
Checkboxes dont display

### ISSUE THREAD

**Issue by lcsqlpete** [creativetimofficial/material-kit#81]
Checkbox doesn't display, just its label.

I tried to include the html by clicking the "Insert code" icon and pasting it in but it appears as empty text.  html was copy/pasted from the example on the material kit website and all css and js files are loaded

Updating this to add that a file input control also does not display.

**Comment by matus1997** [comment]
+1

**Comment by groovemen** [comment]
Hello guys,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
