### ISSUE TITLE
Not able to use it with Webpack

### ISSUE THREAD

**Issue by honey93** [creativetimofficial/material-kit#85]
I have downloaded the material-kit with npm and used it using require("material-kit"), but it's not working. 

How to make it working ?

**Comment by alexandru-paduraru** [comment]
@honey93 thank you for using our product, do you have an example of where you used that? 

Best,
Alex

**Comment by honey93** [comment]
I used *require('material-kit') *after installing material-kit using npm in
my webpack project. I also used  proper loaders in my webpack.config.js but
still not able to use material-kit, it is not producing any affect on the
bootstrap code.



Best,

Honey Thakuria
+91 9924191992 | Linkedin
<https://in.linkedin.com/in/honey-thakuria-b30a3a85>

**Comment by alexandru-paduraru** [comment]
@honey93 please send us an example of the website or the repo so we can check, otherwise, it is impossible to identify the issue.

Best,
Alex

**Comment by groovemen** [comment]
Hello @honey93,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
