### ISSUE TITLE
Carousel Does not automatically Cycle

### ISSUE THREAD

**Issue by rallixt** [creativetimofficial/material-kit#88]
Both on the page I have created and with the one on the index page, the carousel does not automatically cycle through slides. 

I did attempt a few fixes on my own, all of which were unsuccessful, including the more obvious one of adding the script below to my page: 
```
<script type="text/javascript">
  $(document).ready(function() {
    $('.carousel').carousel({
      interval: 1200
    })
  });
</script>
```

I will continue to dig, but wanted to bring this up in case someone else had a quick fix. 

Thank you.

**Comment by alexandru-paduraru** [comment]
@rallixt thank you for using our product. There is a carousel time set to 400.000 in http://demos.creative-tim.com/material-kit/assets/js/material-kit.js. Maybe that it's blocking your carousel time.

Best,
Alex

**Comment by rallixt** [comment]
That was exactly it. I found that in the material-kit.js and adjusted it for my needs. I'm a little embarrassed I didn't find that conflict myself!

Thank you @alexandru-paduraru
