### ISSUE TITLE
Header image error - parallax effect

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/material-kit#89]
The background header image which uses the parallax effect is jumping to a point around the middle of the page as user scrolls page. I thought this was a bug or mistake only affecting my site but I just checked the demo page on your own site and its doing the same thing.

This happens if the user scrolls down past a certain point or if the user refreshes the page while at a lower section.

**Comment by xexclusiv3x** [comment]
This is happening to me too using Google Chrome only.

Can we please get a fix for this?

**Comment by alexandru-paduraru** [comment]
@xexclusiv3x @elvnthaus thank you for using our product and for pointing this out. We teste but we couldn't find the issue. Can you please let us know exactly what Browser and OS you are using? Also a screen record or something that can help us identify it would be great.

Best,
Alex

**Comment by elvnthaus** [comment]
This was addressed for [Material Kit Pro here](https://github.com/creativetimofficial/material-kit-pro/issues/39)

per [@dragosct10](https://github.com/dragosct10)

> To fix this issue please go in your project in assets/js/material-kit.js and search inside of the javascript object materialKitDemo which is on line 303 the function checkScrollForParallax and replace entire function with the following function:
>
> checkScrollForParallax: debounce(function(){

         oVal = ($(window).scrollTop() / 3);
         big_image.css({
             'transform':'translate3d(0,' + oVal +'px,0)',
             '-webkit-transform':'translate3d(0,' + oVal +'px,0)',
             '-ms-transform':'translate3d(0,' + oVal +'px,0)',
             '-o-transform':'translate3d(0,' + oVal +'px,0)'
         });

     }, 6),`
