### ISSUE TITLE
Checkbox with zoom in Chrome

### ISSUE THREAD

**Issue by comerc** [creativetimofficial/material-kit#9]
![checkbox-zoom](https://cloud.githubusercontent.com/assets/1025241/15142334/38fb82d4-16ad-11e6-8c90-eefe25337029.png)

**Comment by alexandru-paduraru** [comment]
@comerc can you please give us more details about the browser/OS etc? Here si how we see it in chrome  50.0.2661.94 on MacBook Retina

<img width="663" alt="screen shot 2016-05-13 at 16 07 54" src="https://cloud.githubusercontent.com/assets/2517758/15248816/e07d0bda-1924-11e6-9b1d-63c06bbbf347.png">

Best,
Alex
