### ISSUE TITLE
Support for navigation drawers?

### ISSUE THREAD

**Issue by cboettig** [creativetimofficial/material-kit#90]
Thanks for sharing this excellent implementation of Google Material Kit design in Bootstrap CSS.  Very elegant and user friendly.  I was wondering if there exists or would be interest in implementing a left-opening navigation drawer, along the [Google's Material.io guidelines](https://material.io/guidelines/patterns/navigation-drawer.html) for navigation menus?  

I'd also appreciate any suggestions on how to adapt the current nav-bar implementation to accomplish this.  

Cheers,

**Comment by tauchvogel** [comment]
I also would like to know how to implement a drawer to the very good material kit template!

**Comment by groovemen** [comment]
Hello @cboettig, thank you for your interest in working with our products, please integrate the code from the following file in your project, and set on the <body> tag the **menu-on-left** class.
[menu-on-left.scss.zip](https://github.com/creativetimofficial/material-kit/files/2159968/menu-on-left.scss.zip)

All the best,
Stefan
