### ISSUE TITLE
date picker left arrow is increasing the date parameter

### ISSUE THREAD

**Issue by boxpositron** [creativetimofficial/material-kit#92]
The left arrow present on the date picker is increasing the date instead of the reducing it. I noticed that when I clicked on the space on the right the arrow but before the year indicator the date reduces. This issue can also be replicated in your demo.

**Comment by groovemen** [comment]
Hello @boxpositron,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
