### ISSUE TITLE
CSS class .form-group-lg overwrites label-color from .has-*

### ISSUE THREAD

**Issue by christof-artho** [creativetimofficial/material-kit#93]
If I add the class `.form-group-lg` to an input-filed (ex. type=text), the class overwrites the label-color from any kind of `.has-*` class.

**Example**
`<div class="form-group label-floating has-error">` => label-color is red (because of the "has-error")
`<div class="form-group form-group-lg label-floating has-error">` => label-color is gray but should be red as well

**Comment by groovemen** [comment]
Hello @christof-artho,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.0.4).

All the best,
Stefan
