### ISSUE TITLE
Navbar shows mobile background on wider screens

### ISSUE THREAD

**Issue by UnknownLuck** [creativetimofficial/material-kit#95]
Hello, I have encountered another issue.  Between, and including, the widths of 992px - 1007px, my background for when the navigation menu is open on slim widths is appearing, while being on the desktop size screen.  That probably sounds confusing but here is a screenshot.
![navbar issue](https://user-images.githubusercontent.com/8964733/33624666-b9850c50-d9ba-11e7-92fb-e775ba7170e5.png)
Would this be due to possible inconsistencies of my media query max-width's?
As before, my site and code is located at unknownluck.github.io.

**Comment by dragosct10** [comment]
Hi, @UnknownLuck! I understand what is the problem but it is confusing for me because on my side this problem is not present. I will give you a video to see how it works on my side. Have you made some changes in the scss?

https://www.dropbox.com/s/dutakwu80bxl4vo/unknown.mov?dl=0

Regards,
Dragos

**Comment by UnknownLuck** [comment]
Interesting.  I have seen this appear in chrome and opera on two separate computers.  I have not changed any scss, mainly out of not knowing much about it. I will take a look and see if I can figure anything out.

**Comment by UnknownLuck** [comment]
Okay, now that I found that, I was able to add a media query for these screen widths and force there to be no background. Not sure what caused this, but I'm glad I finally got this bug out. Thank you!
