### ISSUE TITLE
Timing for Fixed Transparent Navbar to Color on Scroll

### ISSUE THREAD

**Issue by kacinash** [creativetimofficial/material-kit#96]
Is there a place to alter the timing of when the fixed transparent navbar switches to a colored one on scroll? It seems to be occurring late for me, and so my site name is just floating awkwardly over my text for several scrolls.

![screen shot 2017-12-06 at 4 34 49 pm](https://user-images.githubusercontent.com/6652951/33689327-a33bf54a-daa4-11e7-8e23-1f51c9979611.png)

![screen shot 2017-12-06 at 4 35 00 pm](https://user-images.githubusercontent.com/6652951/33689331-a69e7622-daa4-11e7-814b-274ea1ba146a.png)

![screen shot 2017-12-06 at 4 38 52 pm](https://user-images.githubusercontent.com/6652951/33689335-a899d098-daa4-11e7-831a-fe38b7fe2cc9.png)

**Comment by groovemen** [comment]
Hello @kacinash,

Thank you for using our template, please update your project to the latest version (V2.0.4) and at line **158** on `material-kit.js` file you will find the `checkScrollForTransparentNavbar` function from where you can change the timing right there.

All the best, 
Stefan
