### ISSUE TITLE
clickable navbar with hover

### ISSUE THREAD

**Issue by skazhikadyadya** [creativetimofficial/material-kit#98]
Hello! 

Thank you for your nice framework. I have a license, but I don't know where I can add a question. :)

How I can create navbar dropdowns with show menu on hover and link on parent? And how about mobile? 

Can you give me example?

Thank you!

**Comment by dragosct10** [comment]
Hi, @skazhikadyadya! Thank you for using our product. I think this small tutorial will help you to find how to build a dropdown hoverable menu. Please check this [link](https://www.w3schools.com/howto/howto_css_dropdown.asp).

Regards,
Dragos

**Comment by skazhikadyadya** [comment]
Hi, @dragosct10! Thank you for reply! That link, unfortunately show me examples without bootstrap framework. :( Maybe I can show you my site, and you can recommend me implementation? Thank you.

I want to explode menu on parent hover and clickable parent. :) And I have problem with that.

**Comment by dragosct10** [comment]
Hi, @skazhikadyadya! I searched more deeper and I found another tutorial but this time is with the bootstrap framework. Hope this will help you! Please check this [link](https://codepen.io/bsngr/pen/frDqh).

Regards,
Dragos
