### ISSUE TITLE
Problem with inputs using VUE

### ISSUE THREAD

**Issue by 50l3r** [creativetimofficial/material-kit#99]
Hi,

Im using vue with material kit. When i create new DOM elements inputs doesnt display well.

![input](https://i.imgur.com/lVsRHfg.png)

**Comment by alexandru-paduraru** [comment]
@50l3r thank you for using our product. Please add the arrive.js library: https://github.com/FezVrasta/bootstrap-material-design/tree/v3#arrivejs-support We will release an official Vue Material Kit in the next weeks.

Best,
Alex
